[package]
name = "memento-vdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
actix-web = "4.4.0"
